# Using Machine Learning Algorithm and NLP Concept

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Load the Dataset

In [2]:
data=pd.read_csv("Language Detection.csv")

In [3]:
print(data)

                                                    Text Language
0       Nature, in the broadest sense, is the natural...  English
1      "Nature" can refer to the phenomena of the phy...  English
2      The study of nature is a large, if not the onl...  English
3      Although humans are part of nature, human acti...  English
4      [1] The word nature is borrowed from the Old F...  English
...                                                  ...      ...
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

[10337 rows x 2 columns]

In [4]:
data.head()

                                                Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [5]:
data.tail()

                                                    Text Language
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

## Using Scikit-Learn Library

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.naive_bayes import MultinomialNB

## Data Cleaning

In [9]:
data.isnull().sum()

Text        0
Language    0
dtype: int64

In [10]:
data['Language'].value_counts()

Language
English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: count, dtype: int64

## Using numpy library to convert text into number

In [11]:
data.dtypes

Text        object
Language    object
dtype: object

In [12]:
x=np.array(data['Text'])
y=np.array(data['Language'])

In [13]:
print("Text : ", x)

Text :  [' Nature, in the broadest sense, is the natural, physical, material world or universe.'
 '"Nature" can refer to the phenomena of the physical world, and also to life in general.'
 'The study of nature is a large, if not the only, part of science.' ...
 "ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎಲ್ಲವನ್ನೂ ಹೇಳಿದೆ ಮತ್ತು ಅವಳು ಆ ಸಮಯದಿಂದ ತುಂಬಾ ಬದಲಾಗಿದ್ದಾಳೆ."
 'ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ನಾನು ess ಹಿಸಿದ್ದೇನೆ.'
 'ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣುತ್ತಿದ್ದೀರಿ ಆದರೆ ನಾನು ಏನು ನೋಡುತ್ತಿದ್ದೇನೆ ನೀವು ಹೇಗೆ ಅವನಾಗಬಹುದು ನೀವು ಇಬ್ಬರು ತುಂಬಾ ಒಳ್ಳೆಯವರು']

In [14]:
print("Language : ", y)

Language :  ['English' 'English' 'English' ... 'Kannada' 'Kannada' 'Kannada']

In [15]:
data

                                                    Text Language
0       Nature, in the broadest sense, is the natural...  English
1      "Nature" can refer to the phenomena of the phy...  English
2      The study of nature is a large, if not the onl...  English
3      Although humans are part of nature, human acti...  English
4      [1] The word nature is borrowed from the Old F...  English
...                                                  ...      ...
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

[10337 rows x 2 columns]

In [16]:
cv=CountVectorizer()
X=cv.fit_transform(x)

In [17]:
X_train,X_test,y_train, y_test=train_test_split(X,y, test_size=0.33, random_state=42)

In [18]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 110330 stored elements and shape (6925, 39928)>

In [19]:
print(X_train)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 110330 stored elements and shape (6925, 39928)>
  Coords	Values
  (0, 16086)	1
  (0, 1114)	1
  (1, 1603)	1
  (1, 2231)	1
  (1, 9329)	1
  (1, 12874)	1
  (1, 17080)	1
  (1, 7043)	1
  (1, 14776)	1
  (1, 17085)	1
  (1, 24068)	1
  (1, 18699)	1
  (1, 16610)	1
  (2, 24867)	1
  (2, 1603)	1
  (2, 22229)	1
  (2, 3946)	1
  (2, 12169)	1
  (2, 23873)	1
  (2, 11052)	1
  (2, 2969)	1
  (2, 24590)	1
  (2, 6148)	1
  (2, 5585)	1
  (2, 15126)	1
  :	:
  (6923, 13363)	1
  (6923, 1281)	1
  (6923, 17987)	1
  (6923, 24878)	3
  (6923, 7266)	1
  (6923, 1088)	1
  (6923, 10977)	1
  (6923, 10769)	1
  (6923, 22787)	1
  (6923, 24216)	1
  (6924, 18687)	3
  (6924, 27418)	2
  (6924, 16365)	2
  (6924, 1628)	1
  (6924, 13640)	1
  (6924, 847)	1
  (6924, 23198)	1
  (6924, 8967)	1
  (6924, 26282)	1
  (6924, 13233)	1
  (6924, 7351)	1
  (6924, 7364)	1
  (6924, 16367)	1
  (6924, 1972)	1
  (6924, 6461)	1

In [20]:
print(y)

['English' 'English' 'English' ... 'Kannada' 'Kannada' 'Kannada']

## Using Machine Learning Algorithm

### Navie Bayes Algorithm

In [22]:
model=MultinomialNB()

In [23]:
model.fit(X_train, y_train)

MultinomialNB()

In [24]:
model.score(X_test, y_test)

0.977725674091442

In [25]:
user=input("Enter the text :")
data=cv.transform([user]).toarray()
output=model.predict(data)
print(output)

Enter the text : Machine Learning is a Backbone of A.I. and Deep Learning is a Heart of A.I.

['English']

In [26]:
user=input("Enter the text :")
data=cv.transform([user]).toarray()
output=model.predict(data)
print(output)

Enter the text :  मशीन लर्निंग कृत्रिम बुद्धिमत्ता की रीढ़ है और डीप लर्निंग कृत्रिम बुद्धिमत्ता का हृदय है।

['Hindi']

In [28]:
user=input("Enter the text :")
data=cv.transform([user]).toarray()
output=model.predict(data)
print(output)

Enter the text : ಯಂತ್ರ ಕಲಿಕೆ ಎ.ಐ.ನ ಬೆನ್ನೆಲುಬಾಗಿದೆ ಮತ್ತು ಆಳವಾದ ಕಲಿಕೆ ಎ.ಐ.ನ ಹೃದಯವಾಗಿದೆ.

['Kannada']